from turtle import *
Screen()
setup(500, 500)
tracer(0)
a = Turtle()
b = Turtle()
a.width(3)
b.width(3)
a.speed(0)
b.speed(0)
a.ht()
b.ht()
b.up()
b.goto(-70, -130)
b.down()
b.circle(160)
def drawCircle(r):
    for i in range(r):
        a.fd(2.5)
        a.rt(1.8)
a.penup()
a.goto(-70, 30)
a.down()
while True:
    a.clear()
    drawCircle(200)
    a.circle(80)
    Screen().update()
    a.left(1)
done()