import turtle

turtle.Screen().bgcolor("black")
turtle.speed(1)
turtle.begin_fill()
turtle.fillcolor('#1DB954')
turtle.pencolor("#1DB954")
turtle.pensize(0)
turtle.circle(100)
turtle.end_fill()
turtle.penup()
turtle.goto(40,50)
turtle.pendown()
turtle.left(150)
turtle.forward(0)
turtle.pensize(15)
turtle.pencolor('black')
turtle.circle(80,60)
turtle.penup()

turtle.goto(50,85)
turtle.pendown()
turtle.pensize(17)
turtle.right(60)
turtle.forward(0)
turtle.circle(100,60)

turtle.penup()
turtle.goto(60,120)
turtle.pendown()
turtle.pensize(20)
turtle.right(60)
turtle.forward(0)
turtle.circle(120,60)


turtle.done()